### ISSUE TITLE
feature request (ICS support)

### ISSUE THREAD

**Issue by ak2k** [StefanSchroeder/Gocal#10]
Would you consider accepting an ics file (or URL) with events? 

https://en.m.wikipedia.org/wiki/ICalendar

**Comment by StefanSchroeder** [comment]
Sure.

**Comment by StefanSchroeder** [comment]
I have added a first version of ICS support. There is now an undocumented new parameter -ics which can take a filename or an URL and will add the *SUMMARY* flag as text to matching dates.
TODO: currently you can add only one ICS file which is, of course, not optimal.
Try this:

./gocalendar -ics http://www.google.com/calendar/ical/de.german%23holiday%40group.v.calendar.google.com/public/basic.ics -small -p L

to add German holidays to your calendar.

Is this what you were after?

**Comment by StefanSchroeder** [comment]
OK. Please give feedback after testing.
I will definitely add the capability to have more than one ics object on the command-line.
Meanwhile I am considering to remove the proprietary XML event format in favor of ICS.
I love open formats. I just hesitate because ICS is slightly more verbose, and I don't know how to represent images in ICS, a nicety in the gocal format.

**Comment by StefanSchroeder** [comment]
I have now tagged a new version v0.9.2 which includes the -ics feature fully.

**Comment by StefanSchroeder** [comment]
If you would be willing to share a (sanitized of private data) calendar that demonstrates the omission, I can look into it, sparing you the extra work.

**Comment by StefanSchroeder** [comment]
I am closing this one. If you still like to include non-entire-day events, please file a new ticket.
